version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
  - package-ecosystem: "maven"
    directory: "/querydsl-criteria-builder"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
  - package-ecosystem: "maven"
    directory: "/test-backend"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
  - package-ecosystem: "npm"
    directory: "/test-frontend"
    schedule:
      interval: "daily"
    assignees:
      - "PabloLec"
